version: '3.8'
services:
  database:
    image: mysql
    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE: 'jpa'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Admin@123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306,3307 on the container
      - '3306'
      - '3307'

      # Where our data will be persisted
    volumes:
      - ./init.sql:/data/application/init.sql
      - my-db:/var/lib/mysql
  pma:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    environment:
      PMA_HOST: database
      PMA_PORT: 3307
    ports:
      - 81:80
    expose:
      - '81'
  web:
    depends_on:
      - database
    image: io.jotech/jpa
    container_name: web
    restart: always
    ports:
      - '8080:8080'
      - '9990:9990'
    expose:
      # Opens port 8080,9990 on the container
      - '8080'
      - '9990'
  postgres:
    image: postgres:14.1
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data


# Names our volume
volumes:
  my-db:
  postgres-data: